version: '3.8'

services:
  app:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - "8000:8000"

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${user}
      MONGO_INITDB_ROOT_PASSWORD: ${pass}
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb
    ports:
      - ${port}:27017